name: First Workflow
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting #Step-1
        run: echo "Hello world" #For steps, we can execute either script/command or predefined actions
      - name: Print Goodby #Step-2 name
        run: echo "Done, bye thanks!!" 
      
